### PR TITLE
Update dependencies

### PR DESCRIPTION
**Pull request by zwhitchcox**
This PR updates the `usb` dependency (among others) to be compatible with `node 14`

### CODE REVIEW

**Comment by zwhitchcox** [comment]
I've already tested this with a physical device so if everything looks good, you can just approve (and the checks pass)

**Comment by mcraa** [comment]
You mean *above* node 12 right ?

**Comment by zwhitchcox** [comment]
Yes! @mcraa  whoops

**Review by ab77 — APPROVED** [review]

**Review by mcraa — APPROVED** [review]

**Review by builder555 — COMMENTED** [review]
cool!

**Comment by ab77** [comment]
@builder555 @zwhitchcox you should set `secrets: inherit` instead of copying them.

**Comment by ab77** [comment]
@zwhitchcox if you want it to build on multiple node versions (e.g.):

```
diff --git a/package.json b/package.json
index 15f270b..1fb943b 100644
--- a/package.json
+++ b/package.json
@@ -56,5 +56,8 @@
   "homepage": "https://github.com/balena-io-modules/node-beaglebone-usbboot#readme",
   "versionist": {
     "publishedAt": "2021-10-04T15:28:53.807Z"
+  },
+  "engines": {
+    "node": ">=14 < 18"
   }
 }
```

as currently Flowzone falls back to default node 16.x.

**Comment by zwhitchcox** [comment]
Thanks @ab77 ...do you happen to know how I can get rid of the ResinCI checks? Do I just need to create another PR with flowzone already added?

**Comment by zwhitchcox** [comment]
@balena-ci I self-certify!

**Comment by zwhitchcox** [comment]
@balena-ci retest

**Comment by ab77** [comment]
> Thanks @ab77 ...do you happen to know how I can get rid of the ResinCI checks? Do I just need to create another PR with flowzone already added?

you need t remove that `with:` block from flowzone.yml @zwhitchcox

**Comment by zwhitchcox** [comment]
D'oh! Ok, thanks @ab77

**Pull request merged**
